import type {
  Agent,
  AgentLayer,
  AgentPolicy,
  AgentRuntimeState,
  AgentStatus,
  FabioAgentDefinition,
  Zone,
} from "../types.js";
import { refreshAgentRisk } from "../risk.js";

const now = () => new Date().toISOString();

function policy(
  partial: Omit<AgentPolicy, "riskLevel" | "riskNotes">,
): AgentPolicy {
  return { ...partial, riskLevel: "safe", riskNotes: [] };
}

function p(
  sandboxMode: AgentPolicy["sandboxMode"],
  workspaceAccess: AgentPolicy["workspaceAccess"],
  allowed: string[],
  denied: string[],
  elevated: AgentPolicy["elevated"] = "disabled",
): Omit<AgentPolicy, "riskLevel" | "riskNotes"> {
  return {
    sandboxMode,
    sandboxScope: "agent",
    workspaceRoot: "~/.openclaw/sandbox",
    workspaceAccess,
    dockerSandbox: sandboxMode === "all" ? "enabled" : "disabled",
    browserSandbox: allowed.includes("browser") ? "isolated" : "disabled",
    prunePolicy: "on-idle",
    allowedTools: allowed,
    deniedTools: denied,
    toolProfile: "minimal",
    providerPolicy: "inherit",
    sandboxToolPolicy: "inherit",
    subagentToolPolicy: "deny-all",
    elevated,
    agentDir: "",
    authProfile: "local",
  };
}

function def(
  id: string,
  name: string,
  layer: AgentLayer,
  role: string,
  responsibilities: string[],
  inputs: string[],
  outputs: string[],
  status: AgentStatus,
  catalogZone: string,
  mapZone: Zone,
  requiresApprovalFor: string[],
  policyPartial: Omit<AgentPolicy, "riskLevel" | "riskNotes">,
  essential: boolean,
  initialTask?: string,
): FabioAgentDefinition {
  return {
    id,
    name,
    layer,
    role,
    responsibilities,
    inputs,
    outputs,
    status,
    catalogZone,
    mapZone,
    requiresApprovalFor,
    essential,
    initialTask: initialTask ?? (status === "planned" ? "Planejado — nao implantado" : "Inativo"),
    policyTemplate: {
      ...policyPartial,
      agentDir: policyPartial.agentDir || `~/.openclaw/agents/${id}/agent`,
    },
  };
}

/** Catálogo formal FabioOS — fonte única de agentes. */
export const FABIO_AGENT_DEFINITIONS: FabioAgentDefinition[] = [
  def(
    "megatron",
    "MEGATRON",
    "command",
    "Orquestrador central — decompoe tarefas e roteia agentes",
    [
      "Receber comandos do Fabio",
      "Decompor tarefas grandes",
      "Acionar agente correto",
      "Exigir aprovacao humana em acoes sensiveis",
    ],
    ["mensagens do usuario", "eventos n8n", "estados dos agentes"],
    ["plano de acao", "roteamento", "pedido de aprovacao", "log operacional"],
    "planned",
    "Comando Central",
    "Classificação",
    ["execucao destrutiva", "envio externo"],
    p("all", "ro", ["read", "sessions_list", "sessions_send", "sessions_history", "session_status"], ["exec", "write", "edit", "apply_patch", "process", "browser"]),
    true,
  ),
  def(
    "supervisor",
    "Supervisor",
    "security",
    "Auditor de decisao e aprovacao humana",
    [
      "Revisar acoes sensiveis",
      "Aprovar ou bloquear ferramentas perigosas",
      "Validar mensagens antes de envio externo",
    ],
    ["pedidos de execucao", "filas de aprovacao"],
    ["aprovacao", "rejeicao", "escalonamento humano"],
    "active",
    "Aprovação Humana",
    "Aprovação Humana",
    ["envio externo", "shell", "escrita critica", "automacao recorrente"],
    p("off", "ro", ["read", "sessions_list", "sessions_history", "session_status"], ["exec", "write", "edit", "apply_patch", "process", "browser"]),
    true,
    "Fila de aprovacoes vazia",
  ),
  def(
    "guardiao",
    "Guardião",
    "security",
    "Seguranca, permissoes, sandbox e credenciais",
    [
      "Verificar agentDir unico",
      "Detectar exec sem sandbox",
      "Manter Security Matrix",
    ],
    ["policies dos agentes", "alertas"],
    ["alertas de risco", "matriz atualizada"],
    "planned",
    "Security Matrix",
    "GitHub",
    [],
    p("all", "ro", ["read", "sessions_history", "session_status"], ["exec", "write", "edit", "apply_patch", "process", "browser", "gateway"]),
    true,
  ),
  def(
    "roteador",
    "Roteador",
    "command",
    "Classificador de entradas multi-canal",
    [
      "Classificar entrada",
      "Detectar intencao e urgencia",
      "Acionar agente correto",
    ],
    ["WhatsApp", "email", "inbox", "comandos chat"],
    ["classificacao", "prioridade", "roteamento"],
    "planned",
    "Classificação",
    "Classificação",
    [],
    p("all", "ro", ["read", "sessions_send"], ["exec", "write", "edit", "apply_patch", "process"]),
    true,
  ),
  def(
    "memoria",
    "Memória",
    "technical",
    "Estado, contexto e continuidade entre sessoes",
    [
      "Atualizar arquivos de estado",
      "Registrar decisoes e proximos passos",
      "Preparar contexto para novo chat",
    ],
    ["logs de sessao", "decisoes", "STATUS.md"],
    ["PROJECT_STATUS", "CONTEXT_BRIEFING", "resumos"],
    "planned",
    "Memória",
    "Obsidian",
    ["escrita em arquivos de estado"],
    p("all", "rw", ["read", "write", "edit"], ["exec", "process", "browser"]),
    true,
  ),
  def(
    "codex",
    "Codex",
    "technical",
    "Programacao, GitHub, refatoracao e scripts",
    [
      "Criar e corrigir codigo",
      "Refatorar e documentar",
      "Preparar commits",
    ],
    ["issues", "PRs", "logs", "specs"],
    ["codigo", "patches", "documentacao tecnica"],
    "active",
    "GitHub / Código",
    "GitHub",
    ["exec sem sandbox", "push main", "deploy"],
    p("all", "rw", ["read", "write", "edit", "apply_patch", "exec", "process"], ["browser", "gateway"], "restricted"),
    true,
    "Repositorio estavel",
  ),
  def(
    "integrador",
    "Integrador",
    "technical",
    "n8n, APIs, webhooks e MCP",
    [
      "Criar fluxos n8n",
      "Conectar agentes ao Agentarium",
      "Documentar endpoints",
    ],
    ["webhooks", "eventos externos"],
    ["automacoes", "payloads JSON", "integracoes"],
    "planned",
    "n8n / Integrações",
    "n8n",
    ["webhooks publicos", "automacao recorrente"],
    p("all", "rw", ["read", "write", "edit", "browser"], ["exec", "process"]),
    true,
  ),
  def(
    "tecnico-sistema",
    "Técnico de Sistema",
    "technical",
    "PC, VPS, Docker e saude da maquina",
    [
      "Diagnosticar infraestrutura",
      "Verificar containers e portas",
      "Sugerir limpeza segura",
    ],
    ["logs", "metricas", "status servicos"],
    ["diagnostico", "comandos sugeridos"],
    "planned",
    "Sistema / Infraestrutura",
    "n8n",
    ["exec destrutivo", "restart servicos"],
    p("all", "ro", ["read", "exec", "process"], ["write", "edit", "apply_patch"]),
    true,
  ),
  def(
    "observador",
    "Observador",
    "technical",
    "Telemetria, logs e presence no Agentarium",
    [
      "Ler estados dos agentes",
      "Atualizar mapa visual",
      "Detectar erros e sobrecarga",
    ],
    ["eventos backend", "WebSocket"],
    ["presenca visual", "logs laterais"],
    "planned",
    "Telemetria",
    "RAG",
    [],
    p("all", "ro", ["read", "sessions_list", "session_status"], ["exec", "write", "edit", "process"]),
    true,
  ),
  def(
    "arquivista",
    "Arquivista",
    "knowledge",
    "Obsidian, inbox e organizacao de conhecimento",
    [
      "Capturar e limpar texto",
      "Criar notas Markdown",
      "Mover conteudo da Inbox",
    ],
    ["capturas", "PDFs", "conversas"],
    ["notas", "tags", "changelog"],
    "active",
    "Obsidian",
    "Inbox",
    ["movimentacao em massa", "delete"],
    p("all", "rw", ["read", "write", "edit"], ["exec", "process", "browser", "gateway"]),
    true,
    "Monitorando inbox",
  ),
  def(
    "pesquisador",
    "Pesquisador",
    "knowledge",
    "RAG, web, fontes e sintese",
    [
      "Pesquisar e comparar",
      "Alimentar RAG",
      "Criar fichamentos",
    ],
    ["links", "PDFs", "queries RAG"],
    ["relatorios", "mapas conceituais"],
    "active",
    "RAG / Pesquisa",
    "RAG",
    [],
    p("all", "ro", ["read", "browser"], ["exec", "write", "edit", "apply_patch", "process"]),
    true,
    "Indice vetorial pronto",
  ),
  def(
    "curador",
    "Curador",
    "knowledge",
    "Qualidade, duplicidade e linkagem do vault",
    [
      "Detectar duplicatas",
      "Sugerir backlinks e MOCs",
      "Melhorar taxonomia",
    ],
    ["notas arquivadas"],
    ["indices", "links", "unificacoes"],
    "planned",
    "Curadoria",
    "Obsidian",
    ["delete", "merge em massa"],
    p("all", "rw", ["read", "edit"], ["exec", "process", "browser"]),
    false,
  ),
  def(
    "professor-autor",
    "Professor-Autor",
    "school",
    "Producao didatica — provas, revisoes, gabaritos",
    [
      "Criar provas e revisoes",
      "Adaptar linguagem por serie",
      "Preparar material para Docs",
    ],
    ["conteudo bruto", "habilidades BNCC"],
    ["provas", "gabaritos", "revisoes"],
    "planned",
    "Produção Didática",
    "Obsidian",
    ["publicacao externa"],
    p("all", "rw", ["read", "write", "edit"], ["exec", "process"]),
    true,
  ),
  def(
    "pietra",
    "Pietra",
    "school",
    "Atendimento escolar inicial",
    [
      "Ler mensagens recebidas",
      "Classificar urgencia",
      "Sugerir resposta",
    ],
    ["WhatsApp", "mensagens escolares"],
    ["rascunhos", "registros de atendimento"],
    "active",
    "WhatsApp / Escola",
    "WhatsApp",
    ["envio para responsavel", "promessas institucionais"],
    p("all", "ro", ["read", "sessions_send", "sessions_history"], ["exec", "write", "edit", "apply_patch", "process", "browser", "gateway"]),
    true,
    "Aguardando mensagens",
  ),
  def(
    "secretaria-escolar",
    "Secretaria Escolar",
    "school",
    "Prazos, calendarios e comunicados",
    [
      "Registrar provas e reunioes",
      "Avisar prazos",
      "Montar cronogramas",
    ],
    ["calendario", "eventos"],
    ["lembretes", "cronogramas"],
    "planned",
    "Calendário Escolar",
    "WhatsApp",
    ["comunicados externos"],
    p("all", "rw", ["read", "write", "edit"], ["exec", "process"]),
    true,
  ),
  def(
    "avaliador",
    "Avaliador",
    "school",
    "Correcao, gabaritos e dados de prova",
    [
      "Comparar respostas",
      "Gerar tabelas por aluno",
      "Identificar questoes problematicas",
    ],
    ["gabaritos", "respostas"],
    ["relatorios de correcao"],
    "planned",
    "Correção / Avaliação",
    "Obsidian",
    ["publicacao de notas"],
    p("all", "rw", ["read", "write"], ["exec", "process", "browser"]),
    true,
  ),
  def(
    "planejador-pedagogico",
    "Planejador Pedagógico",
    "school",
    "Aulas, sequencia e progressao didatica",
    [
      "Criar planos de aula",
      "Sequenciar modulos",
      "Organizar retomadas",
    ],
    ["conteudo", "resultados de prova"],
    ["planos", "sequencias", "objetivos"],
    "planned",
    "Planejamento",
    "Obsidian",
    [],
    p("all", "rw", ["read", "write", "edit"], ["exec", "process"]),
    true,
  ),
  def(
    "comunicador-institucional",
    "Comunicador Institucional",
    "school",
    "Mensagens formais para pais, alunos e coordenacao",
    [
      "Redigir comunicados",
      "Ajustar tom institucional",
      "Encaminhar ao Supervisor",
    ],
    ["briefings", "rascunhos"],
    ["mensagens formais"],
    "planned",
    "Comunicação",
    "WhatsApp",
    ["send_external"],
    p("all", "rw", ["read", "write"], ["send_external", "exec", "process"]),
    true,
  ),
  def(
    "financeiro",
    "Financeiro",
    "finance",
    "Despesas, faturas e planejamento",
    [
      "Organizar gastos",
      "Calcular saldo e dividas",
      "Gerar alertas",
    ],
    ["faturas", "extratos"],
    ["relatorios financeiros", "alertas"],
    "planned",
    "Finanças",
    "Inbox",
    ["decisoes de investimento", "send_external"],
    p("all", "rw", ["read", "write"], ["exec", "process", "send_external"]),
    true,
  ),
  def(
    "risco-trader",
    "Risco Trader",
    "finance",
    "Gestao de risco e disciplina operacional",
    [
      "Verificar limite diario",
      "Impedir overtrade",
      "Registrar diario de trade",
    ],
    ["operacoes", "limites"],
    ["auditoria de risco", "revisao pos-op"],
    "planned",
    "Trader / Risco",
    "RAG",
    ["execute_trade", "send_order"],
    p("all", "rw", ["read", "write"], ["execute_trade", "send_order", "exec", "process"]),
    true,
  ),
  def(
    "relator",
    "Relator",
    "finance",
    "Relatorios, KPIs e resumos periodicos",
    [
      "Criar resumo diario/semanal",
      "Mostrar pendencias humanas",
      "Mostrar gargalos",
    ],
    ["STATUS", "agentes", "decisoes"],
    ["relatorios", "KPIs"],
    "planned",
    "Relatórios",
    "Obsidian",
    [],
    p("all", "rw", ["read", "write"], ["exec", "process"]),
    false,
  ),
  def(
    "crm",
    "CRM",
    "personal",
    "Pessoas, contatos e historico de interacao",
    [
      "Registrar pessoas",
      "Preparar briefing pre-reuniao",
    ],
    ["contatos", "historico"],
    ["briefings", "pendencias"],
    "planned",
    "CRM",
    "Inbox",
    [],
    p("all", "rw", ["read", "write", "edit"], ["exec", "process"]),
    false,
  ),
  def(
    "email-inbox",
    "Email Inbox",
    "personal",
    "Triagem de e-mails",
    [
      "Separar urgente/responder/arquivar",
      "Criar rascunhos",
    ],
    ["emails"],
    ["classificacao", "rascunhos"],
    "planned",
    "E-mail",
    "Inbox",
    ["envio automatico"],
    p("all", "ro", ["read", "write"], ["exec", "process", "send_external"]),
    false,
  ),
  def(
    "calendario",
    "Calendário",
    "personal",
    "Agenda e rotina",
    [
      "Preparar briefing diario",
      "Alertar conflitos",
    ],
    ["agenda", "eventos"],
    ["briefings", "alertas"],
    "planned",
    "Calendário",
    "Inbox",
    [],
    p("all", "rw", ["read", "write", "edit"], ["exec", "process"]),
    false,
  ),
  def(
    "cartografo",
    "Cartógrafo",
    "interface",
    "Mapa visual do Agentarium",
    [
      "Mapear agente para zona",
      "Organizar tiles e layout",
    ],
    ["estados", "zonas"],
    ["layout visual", "posicionamento"],
    "planned",
    "Interface / HUD",
    "GitHub",
    [],
    p("all", "rw", ["read", "write", "edit"], ["exec", "process"]),
    false,
  ),
  def(
    "designer-sistema",
    "Designer de Sistema",
    "interface",
    "Estetica 16-bit tatica",
    [
      "Definir tokens CSS",
      "Manter coerencia visual",
    ],
    ["design tokens", "screenshots"],
    ["paleta", "sprites", "layout"],
    "planned",
    "Design / Pixel Ops",
    "GitHub",
    [],
    p("all", "rw", ["read", "write", "edit"], ["exec", "process"]),
    false,
  ),
  def(
    "saude-bemestar",
    "Saúde / Bem-estar",
    "personal",
    "Registro pessoal restrito — sem decisao medica",
    [
      "Registrar dados do usuario",
      "Organizar historico",
      "Nunca prescrever",
    ],
    ["registros pessoais"],
    ["historico", "perguntas para consulta"],
    "planned",
    "Bem-estar",
    "Inbox",
    ["medical_decision", "prescription"],
    p("all", "rw", ["read", "write"], ["medical_decision", "prescription", "exec", "process"]),
    false,
  ),
];

export const ACTIVE_AGENT_IDS = FABIO_AGENT_DEFINITIONS.filter(
  (d) => d.status === "active",
).map((d) => d.id);

export function getDefinition(id: string): FabioAgentDefinition | undefined {
  return FABIO_AGENT_DEFINITIONS.find((d) => d.id === id);
}

export function definitionToAgent(
  d: FabioAgentDefinition,
  overrides?: Partial<Pick<Agent, "state" | "task" | "zone" | "updatedAt">>,
): Agent {
  const base: Agent = {
    id: d.id,
    name: d.name,
    layer: d.layer,
    status: d.status,
    role: d.role,
    responsibilities: d.responsibilities,
    inputs: d.inputs,
    outputs: d.outputs,
    requiresApprovalFor: d.requiresApprovalFor,
    essential: d.essential,
    catalogZone: d.catalogZone,
    state: (overrides?.state ?? "idle") as AgentRuntimeState,
    task: overrides?.task ?? d.initialTask,
    zone: overrides?.zone ?? d.mapZone,
    updatedAt: overrides?.updatedAt ?? now(),
    policy: policy({ ...d.policyTemplate, agentDir: d.policyTemplate.agentDir }),
  };
  return refreshAgentRisk(base);
}

export function buildInitialActiveAgents(): Agent[] {
  return FABIO_AGENT_DEFINITIONS.filter((d) => d.status === "active").map((d) =>
    definitionToAgent(d, {
      state: "idle",
      task: d.initialTask,
      zone: d.mapZone,
    }),
  );
}

export function buildFullCatalog(liveAgents: Map<string, Agent>): Agent[] {
  return FABIO_AGENT_DEFINITIONS.map((d) => {
    const live = liveAgents.get(d.id);
    if (live && d.status === "active") return refreshAgentRisk(live);
    return definitionToAgent(d);
  }).sort((a, b) => a.name.localeCompare(b.name, "pt-BR"));
}

export const LAYER_LABELS: Record<AgentLayer, string> = {
  command: "Comando",
  security: "Seguranca",
  technical: "Tecnico",
  knowledge: "Conhecimento",
  school: "Escola",
  finance: "Financeiro",
  interface: "Interface",
  personal: "Pessoal",
};
